export const DEFAULT_CATEGORIES = [
    { name: 'Food', icon: '🍔', type: 'expense', description: '' },
    { name: 'Social Life', icon: '🍻', type: 'expense', description: '' },
    { name: 'Transport', icon: '🚌', type: 'expense', description: '' },
    { name: 'HouseHold', icon: '🏠', type: 'expense', description: '' },
    { name: 'Apparel', icon: '👗', type: 'expense', description: '' },
    { name: 'Beauty', icon: '💅', type: 'expense', description: '' },
    { name: 'Health', icon: '💊', type: 'expense', description: '' },
    { name: 'Education', icon: '🎓', type: 'expense', description: '' },
    { name: 'Gift', icon: '🎁', type: 'expense', description: '' },
    { name: 'Other', icon: '🔖', type: 'expense', description: '' },
    { name: 'Allowance', icon: '🧒', type: 'income', description: '' },
    { name: 'Salary', icon: '💼', type: 'income', description: '' },
    { name: 'Petty Cash', icon: '💵', type: 'income', description: '' },
    { name: 'Bonus', icon: '🎉', type: 'income', description: '' },
    { name: 'Other', icon: '➕', type: 'income', description: '' },
    { name: 'Other', icon: '➕', type: 'expense', description: '' },
];
